[package]
name = "tcp-socket"
version = "0.1.0"
authors = ["Cyan Tarek <cyantarek.cg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
